# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x11\x62ookstore.payment\"\"\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"!\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xfd\x01\n\x0ePaymentService\x12P\n\x07Prepare\x12!.bookstore.payment.PrepareRequest\x1a\".bookstore.payment.PrepareResponse\x12M\n\x06\x43ommit\x12 .bookstore.payment.CommitRequest\x1a!.bookstore.payment.CommitResponse\x12J\n\x05\x41\x62ort\x12\x1f.bookstore.payment.AbortRequest\x1a .bookstore.payment.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=36
  _globals['_PREPAREREQUEST']._serialized_end=70
  _globals['_PREPARERESPONSE']._serialized_start=72
  _globals['_PREPARERESPONSE']._serialized_end=104
  _globals['_COMMITREQUEST']._serialized_start=106
  _globals['_COMMITREQUEST']._serialized_end=139
  _globals['_COMMITRESPONSE']._serialized_start=141
  _globals['_COMMITRESPONSE']._serialized_end=174
  _globals['_ABORTREQUEST']._serialized_start=176
  _globals['_ABORTREQUEST']._serialized_end=208
  _globals['_ABORTRESPONSE']._serialized_start=210
  _globals['_ABORTRESPONSE']._serialized_end=242
  _globals['_PAYMENTSERVICE']._serialized_start=245
  _globals['_PAYMENTSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
