# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x15\x62ookstore.suggestions\"*\n\x08\x42ookItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\";\n\tOrderData\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.bookstore.suggestions.BookItem\"n\n\x11\x43\x61\x63heOrderRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x13\n\x0bvectorClock\x18\x02 \x03(\x05\x12\x33\n\torderData\x18\x03 \x01(\x0b\x32 .bookstore.suggestions.OrderData\"0\n\x12\x43\x61\x63heOrderResponse\x12\x1a\n\x12updatedVectorClock\x18\x01 \x03(\x05\"B\n\x1aGenerateSuggestionsRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x13\n\x0bvectorClock\x18\x02 \x03(\x05\"4\n\tBookEntry\x12\x12\n\nbook_title\x18\x01 \x01(\t\x12\x13\n\x0b\x62ook_author\x18\x02 \x01(\t\"h\n\x13SuggestionsResponse\x12\x35\n\x0bsuggestions\x18\x01 \x03(\x0b\x32 .bookstore.suggestions.BookEntry\x12\x1a\n\x12updatedVectorClock\x18\x02 \x03(\x05\" \n\x0b\x42ookRequest\x12\x11\n\tbook_name\x18\x01 \x01(\t2\xcd\x02\n\x12SuggestionsService\x12\x61\n\nCacheOrder\x12(.bookstore.suggestions.CacheOrderRequest\x1a).bookstore.suggestions.CacheOrderResponse\x12t\n\x13GenerateSuggestions\x12\x31.bookstore.suggestions.GenerateSuggestionsRequest\x1a*.bookstore.suggestions.SuggestionsResponse\x12^\n\x0cSuggestBooks\x12\".bookstore.suggestions.BookRequest\x1a*.bookstore.suggestions.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKITEM']._serialized_start=44
  _globals['_BOOKITEM']._serialized_end=86
  _globals['_ORDERDATA']._serialized_start=88
  _globals['_ORDERDATA']._serialized_end=147
  _globals['_CACHEORDERREQUEST']._serialized_start=149
  _globals['_CACHEORDERREQUEST']._serialized_end=259
  _globals['_CACHEORDERRESPONSE']._serialized_start=261
  _globals['_CACHEORDERRESPONSE']._serialized_end=309
  _globals['_GENERATESUGGESTIONSREQUEST']._serialized_start=311
  _globals['_GENERATESUGGESTIONSREQUEST']._serialized_end=377
  _globals['_BOOKENTRY']._serialized_start=379
  _globals['_BOOKENTRY']._serialized_end=431
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=433
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=537
  _globals['_BOOKREQUEST']._serialized_start=539
  _globals['_BOOKREQUEST']._serialized_end=571
  _globals['_SUGGESTIONSSERVICE']._serialized_start=574
  _globals['_SUGGESTIONSSERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
