# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import suggestions_pb2 as suggestions__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in suggestions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuggestionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CacheOrder = channel.unary_unary(
                '/bookstore.suggestions.SuggestionsService/CacheOrder',
                request_serializer=suggestions__pb2.CacheOrderRequest.SerializeToString,
                response_deserializer=suggestions__pb2.CacheOrderResponse.FromString,
                _registered_method=True)
        self.GenerateSuggestions = channel.unary_unary(
                '/bookstore.suggestions.SuggestionsService/GenerateSuggestions',
                request_serializer=suggestions__pb2.GenerateSuggestionsRequest.SerializeToString,
                response_deserializer=suggestions__pb2.SuggestionsResponse.FromString,
                _registered_method=True)
        self.SuggestBooks = channel.unary_unary(
                '/bookstore.suggestions.SuggestionsService/SuggestBooks',
                request_serializer=suggestions__pb2.BookRequest.SerializeToString,
                response_deserializer=suggestions__pb2.SuggestionsResponse.FromString,
                _registered_method=True)


class SuggestionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CacheOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSuggestions(self, request, context):
        """(f) generate suggestions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestBooks(self, request, context):
        """old single-shot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CacheOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheOrder,
                    request_deserializer=suggestions__pb2.CacheOrderRequest.FromString,
                    response_serializer=suggestions__pb2.CacheOrderResponse.SerializeToString,
            ),
            'GenerateSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSuggestions,
                    request_deserializer=suggestions__pb2.GenerateSuggestionsRequest.FromString,
                    response_serializer=suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
            'SuggestBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestBooks,
                    request_deserializer=suggestions__pb2.BookRequest.FromString,
                    response_serializer=suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.suggestions.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookstore.suggestions.SuggestionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CacheOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.suggestions.SuggestionsService/CacheOrder',
            suggestions__pb2.CacheOrderRequest.SerializeToString,
            suggestions__pb2.CacheOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.suggestions.SuggestionsService/GenerateSuggestions',
            suggestions__pb2.GenerateSuggestionsRequest.SerializeToString,
            suggestions__pb2.SuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.suggestions.SuggestionsService/SuggestBooks',
            suggestions__pb2.BookRequest.SerializeToString,
            suggestions__pb2.SuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
